cache:
  paths:
    - node_modules/

stages:
  - test
  - release

before_script:
  - yarn

test:node:10:
  image: node:10
  stage: test
  script:
    - yarn start --owner flotwig --repo get-touching-prs '**/*'

test:node:12:
  image: node:12
  stage: test
  script:
    - yarn start --owner flotwig --repo get-touching-prs '**/*'

release:
  image: node:12
  only:
    - master
  stage: release
  script:
    - git remote set-url origin https://github.com/flotwig/get-touching-prs.git
    - yarn release
